{% set name = "castoredc_api" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/castoredc_api-{{ version }}.tar.gz
  sha256: bf89dcd5b622d28af454b52cecee52256419e060d9c9e1920dbe2dfc2138f154

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - httpx >=0.19.0
    - numpy >=1.21.1
    - openpyxl >=3.0.7
    - pandas >=1.3.1
    - python >=3.8
    - tqdm >=4.62.0

test:
  imports:
    - castoredc_api
    - castoredc_api.auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reiniervlinschoten/castoredc_api
  summary: Python wrapper for the Castor EDC API
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - reiniervlinschoten
